name: push_on_master

on: 
  push:
    branches:
      - master

jobs:
  test:
    runs-on: macOS-latest
    strategy:
        matrix:
          destination: ['platform=iOS Simulator,OS=13.1,name=iPhone 11 Pro']
    steps:
    - uses: actions/checkout@v1
    - name: macOS version
      run: sw_vers
    - name: Simulators
      run: xcrun instruments -s
    - name: Pod install
      run: bundle && bundle exec pod install
    - name: xcode test
      run: xcodebuild test -workspace QiitaAPIKit.xcworkspace -scheme QiitaAPIKit -destination '${{matrix.destination}}'
