name: test

on: [pull_request]

jobs:
  latest:
    runs-on: macOS-latest
    strategy:
        matrix:
          destination: ['platform=iOS Simulator,OS=13.3,name=iPhone 11 Pro']
    steps:
    - uses: actions/checkout@v1
    - name: macOS version
      run: sw_vers
    - name: List Xcode
      run: ls /Applications/Xcode*
    - name: Simulators
      run: xcrun instruments -s
    - name: Pod install
      run: bundle && bundle exec pod install
    - name: Lint this package
      run: make lint
    - name: xcode test
      run: xcodebuild test -workspace QiitaAPIKit.xcworkspace -scheme QiitaAPIKit -destination '${{matrix.destination}}'
